const {test} = require('node:test');
const assert = require('node:assert/strict');
const {chromium, devices} = require('playwright');
const {spawn} = require('node:child_process');
const path = require('node:path');

async function openVocabulary(t, options = {}) {
  const server = spawn('python', ['-m', 'http.server', '0', '--bind', '127.0.0.1', '--directory', path.resolve(__dirname, '../../frontend')], {env: {...process.env, PYTHONUNBUFFERED: '1'}});
  t.after(() => server.kill());
  const origin = await new Promise((resolve, reject) => {
    server.stdout.on('data', data => {const match = data.toString().match(/port (\d+)/); if (match) resolve(`http://127.0.0.1:${match[1]}`);});
    server.on('error', reject);
    server.on('exit', code => reject(new Error(`Static server exited: ${code}`)));
  });
  const browser = await chromium.launch({executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', args: ['--no-sandbox']});
  t.after(() => browser.close());
  const page = await browser.newPage({...options});
  const errors = []; const writes = []; const external = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => {
    if (request.method() !== 'GET') writes.push(request.url());
    if (!request.url().startsWith(origin)) external.push(request.url());
  });
  await page.goto(`${origin}/vocabulary.html`);
  return {page, errors, writes, external};
}
test('teacher bulk list reaches homework, and emergent words require approval for cards', async t => {
  const {page, errors, writes} = await openVocabulary(t);
  await page.locator('#list-title').fill('Presentation Unit 2');
  await page.locator('#list-source').fill('Fictional slides');
  await page.locator('#word-list').fill('wonder; удивляться; I wonder.\nmoonlit; лунный; A garden.');
  await page.locator('#save-list').click();
  assert.match(await page.locator('#vocab-lists').textContent(), /Presentation Unit 2/);
  await page.locator('#vocab-student').click();
  await page.locator('#list-title').fill('Found in a story');
  await page.locator('#word-list').fill('stardust; звёздная пыль; Tiny stardust.');
  await page.locator('#save-list').click();
  assert.match(await page.locator('#vocab-lists').textContent(), /На проверке/);
  assert.match(await page.locator('.learning-progress').textContent(), /из 5/);
  await page.locator('#vocab-teacher').click();
  await page.getByRole('button', {name: 'Одобрить для карточек группы'}).click();
  await page.locator('#vocab-student').click();
  assert.match(await page.locator('.learning-progress').textContent(), /из 6/);
  await page.locator('#vocab-teacher').click();
  await page.locator('#vocab-homework').click();
  await page.locator('#new-task').click();
  await page.locator('#assignment-word-list').selectOption({label: 'Presentation Unit 2'});
  assert.equal(await page.locator('#assignment-vocabulary').inputValue(), 'wonder\nmoonlit');
  assert.deepEqual(errors, []); assert.deepEqual(writes, []);
});
test('student cards record progress without farming, ranking is opt-in and cross-group is team-only', async t => {
  const {page, errors} = await openVocabulary(t, {...devices['iPhone 13']});
  await page.locator('#vocab-student').click();
  assert.equal(await page.locator('#rank-opt-in').isChecked(), false);
  assert.doesNotMatch(await page.locator('.own-group-rank').allTextContents().then(x=>x.join(' ')), /Silver Fern/);
  await page.getByRole('button', {name: '👀 Показать', exact: true}).click();
  await page.getByRole('button', {name: /🙂 Хорошо/}).click();
  assert.match(await page.locator('.learning-progress').textContent(), /повторений: 1 · streak: 1/);
  await page.locator('#rank-opt-in').check();
  assert.match((await page.locator('.own-group-rank').allTextContents()).join(' '), /Silver Fern1 XP/);
  const teamText = (await page.locator('.team-rank').allTextContents()).join(' ');
  assert.doesNotMatch(teamText, /Silver|Amber|Fern|Willow/);
  for (const width of [320, 375, 390, 430]) {await page.setViewportSize({width, height: 844}); assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));}
  await page.reload(); await page.locator('#vocab-student').click();
  assert.match(await page.locator('.learning-progress').textContent(), /повторений: 0 · streak: 0/);
  assert.deepEqual(errors, []);
});
test('one appointed editor per group can use the photo workflow, replacement revokes access', async t => {
  const {page, errors} = await openVocabulary(t);
  await page.locator('#card-editor-group').selectOption('demo-group-3');
  await page.locator('#card-editor-student').selectOption('demo-group-3-fern');
  await page.locator('#vocab-student').click();
  assert(await page.locator('#board-photo').isDisabled());
  assert(!(await page.locator('#board-workspace').isVisible()));
  await page.locator('#vocab-teacher').click();
  await page.locator('#card-editor-group').selectOption('demo-group-1');
  await page.locator('#card-editor-student').selectOption('demo-student-1');
  await page.locator('#vocab-student').click();
  assert(!(await page.locator('#board-photo').isDisabled()));
  assert(await page.locator('#board-workspace').isVisible());
  await page.locator('#vocab-teacher').click();
  await page.locator('#card-editor-student').selectOption('demo-student-2');
  await page.locator('#vocab-student').click();
  assert(await page.locator('#board-photo').isDisabled());
  assert(await page.locator('#save-list').isEnabled()); // emergent suggestions remain available
  assert.deepEqual(errors, []);
});
test('real local OCR turns a synthetic board photo into a reviewed draft without external requests', {timeout: 90000}, async t => {
  const {page, errors, writes, external} = await openVocabulary(t);
  const data = await page.evaluate(() => {const canvas = document.createElement('canvas'); canvas.width = 800; canvas.height = 300; const context = canvas.getContext('2d'); context.fillStyle = 'white'; context.fillRect(0,0,800,300); context.fillStyle = 'black'; context.font = '48px Arial'; context.fillText('moonlit', 40, 70); context.fillText('wonder', 40, 150); context.fillText('stardust', 40, 230); return canvas.toDataURL('image/png').split(',')[1];});
  await page.locator('#board-photo').setInputFiles({name: 'synthetic-board.png', mimeType: 'image/png', buffer: Buffer.from(data, 'base64')});
  await page.locator('#board-preview img').waitFor();
  await page.locator('#recognize-board').click();
  await page.getByText('Черновик распознан. Исправь ошибки и оставь одну запись на строку; затем перенеси в список.', {exact: true}).waitFor({timeout: 60000});
  const draft = await page.locator('#board-text').inputValue();
  assert.match(draft, /moonlit/i); assert.match(draft, /stardust/i);
  assert.equal(await page.locator('.word-list-card').count(), 1);
  await page.locator('#apply-board').click();
  assert.match(await page.locator('#word-list').inputValue(), /wonder/i);
  assert.equal(await page.locator('.word-list-card').count(), 1);
  assert.deepEqual(errors, []); assert.deepEqual(writes, []);
  assert.deepEqual(external.filter(url => /^https?:/.test(url)), []);
});
test('definition-first cards reveal rich answer and translation independently on iPhone', async t => {
  const {page, errors} = await openVocabulary(t, {...devices['iPhone 13']});
  await page.locator('#card-template').click();
  const draft = JSON.parse(await page.locator('#word-list').inputValue());
  assert.equal(draft[0].term,'searing pain'); assert.deepEqual(draft[0].antonyms,['dull ache','mild discomfort']);
  await page.locator('#vocab-student').click();
  assert.match(await page.locator('.card-definition').textContent(), /Sharp, intense burning/);
  assert.equal(await page.locator('.flashcard h3').count(),0);
  await page.getByRole('button',{name:'👀 Показать',exact:true}).click();
  assert.equal(await page.locator('.flashcard h3').textContent(),'searing pain');
  assert.match(await page.locator('.flashcard').textContent(),/Syn: burning pain/);
  assert.match(await page.locator('.flashcard').textContent(),/Coll: searing pain in the chest/);
  assert.equal(await page.locator('.card-example strong').textContent(),'searing pain');
  assert(!(await page.locator('#card-translation').isVisible()));
  await page.getByRole('button',{name:'🇷🇺 Показать перевод',exact:true}).click();
  assert(await page.locator('#card-translation').isVisible());
  assert.equal(await page.locator('#card-translation').textContent(),'жгучая боль');
  await page.getByRole('button',{name:'🇷🇺 Скрыть перевод',exact:true}).click();
  assert(!(await page.locator('#card-translation').isVisible()));
  assert.equal(await page.locator('.training-actions button').count(),4);
  await page.getByRole('button',{name:/🙁 Трудно/}).click();
  assert.equal(await page.locator('.flashcard h3').count(),0);
  assert.equal(await page.locator('#card-translation').count(),0);
  assert.match(await page.locator('.learning-progress').textContent(),/повторений: 1/);
  assert.deepEqual(errors,[]);
});
test('rich card import is limited to appointed editors and still requires teacher approval', async t => {
  const {page, errors} = await openVocabulary(t);
  const card = {term:'<img src=x onerror=alert(1)>',definition:'A literal text example.',meaning:'пример',synonyms:['safe']};
  await page.locator('#vocab-student').click();
  await page.locator('#list-title').fill('Rich draft'); await page.locator('#word-list').fill(JSON.stringify([card]));
  await page.locator('#save-list').click(); assert.match(await page.locator('#word-error').textContent(),/назначенный редактор/);
  await page.locator('#vocab-teacher').click(); await page.locator('#card-editor-student').selectOption('demo-student-1');
  await page.locator('#vocab-student').click(); await page.locator('#save-list').click();
  assert.match(await page.locator('#vocab-lists').textContent(),/Rich draft/);
  assert.equal(await page.locator('#vocab-lists img').count(),0);
  assert.match(await page.locator('.learning-progress').textContent(),/из 3/);
  await page.locator('#vocab-teacher').click(); await page.getByRole('button',{name:'Одобрить для карточек группы'}).click();
  await page.locator('#vocab-student').click(); assert.match(await page.locator('.learning-progress').textContent(),/из 4/);
  assert.deepEqual(errors,[]);
});
